# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
recipe: default.v1
language: en

pipeline:
# https://rasa.com/docs/rasa/tuning-your-model
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "rasa/LaBSE"
  cache_dir: null
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 3
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 8
- name: LogisticRegressionClassifier
  C: 10
  max_iter: 500
  solver: lbfgs
  tol: 0.0001
  random_state: 99
  ranking_length: 10
- name: CRFEntityExtractor
# - name: DIETClassifier
#   epochs: 200
#   constrain_similarities: True
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.2
  ambiguity_threshold: 0.1


policies:
# https://rasa.com/docs/rasa/policies
# - name: MemoizationPolicy

- name: RulePolicy
  core_fallback_threshold: 0.2
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: True
  restrict_rules: True
  check_for_contradictions: True

# - name: UnexpecTEDIntentPolicy
#   max_history: 5
#   epochs: 100

- name: TEDPolicy
  max_history: 3
  epochs: 100
  constrain_similarities: True
