# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
recipe: default.v1
language: en

pipeline:
# https://rasa.com/docs/rasa/tuning-your-model
- name: SpacyNLP
  model: en_core_web_md
# - name: WhitespaceTokenizer
- name: SpacyTokenizer
# dense featurizer due to SklearnIntentClassifier
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 3
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 8
- name: SklearnIntentClassifier
  C: [1, 10, 100]
  kernels: ["linear"]
  gamma: [0.1]
  max_cross_validation_folds: 3
  scoring_function: "f1_weighted"
- name: DIETClassifier
  intent_classification: False
  epochs: 200
  constrain_similarities: True
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.2
  ambiguity_threshold: 0.1


policies:
# https://rasa.com/docs/rasa/policies
# - name: MemoizationPolicy

- name: RulePolicy
  core_fallback_threshold: 0.2
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: True
  restrict_rules: True
  check_for_contradictions: True

# - name: UnexpecTEDIntentPolicy
#   max_history: 5
#   epochs: 100

- name: TEDPolicy
  max_history: 3
  epochs: 100
  constrain_similarities: True
